# Generated by Django 3.1.7 on 2021-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210224_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/static/main/img/recipe/depositphotos_269592716-stock-photo-thumbnail-images-placeholder-forums-blogs.jpg', upload_to='img/recipe'),
        ),
    ]
