# Generated by Django 3.1.7 on 2021-08-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210731_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficult_l',
            field=models.CharField(default='Легко', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(default='/static/main/img/recipe/depositphotos_269592716-stock-photo-thumbnail-images-placeholder-forums-blogs.jpg', upload_to='img/steps')),
                ('text', models.TextField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe')),
            ],
        ),
    ]
