# Generated by Django 3.1.7 on 2021-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210819_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/static/main/img/recipe/depositphotos_269592716-stock-photo-thumbnail-images-placeholder-forums-blogs.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(default='/static/main/img/recipe/depositphotos_269592716-stock-photo-thumbnail-images-placeholder-forums-blogs.jpg', upload_to=''),
        ),
    ]
