# Generated by Django 3.1.7 on 2021-08-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210820_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
